version: '3'
services:
    database:
        image: mongo:4.2
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${DATABASE_PRIMARY_USERNAME}
            MONGO_INITDB_ROOT_PASSWORD: ${DATABASE_PRIMARY_PASSWORD}
        ports:
            - ${DATABASE_PRIMARY_PORT}:27017
        volumes:
            - ./container/mongo/data:/data/db
        networks:
            - pc_network
    appapi:
        build: ./container/python/
        volumes:
            - ./appApi/:/project/
        command: 'gunicorn --chdir ${API_PROJECT_NAME} -w ${API_GUNICORN_WORKER} --bind :8000 ${API_PROJECT_NAME}.wsgi:application'
        networks:
            - pc_network
    appweb:
        build: ./container/python/
        volumes:
            - ./appWeb/:/project/
        command: 'gunicorn --chdir ${WEB_PROJECT_NAME} -w ${WEB_GUNICORN_WORKER} --bind :8000 ${WEB_PROJECT_NAME}.wsgi:application'
        networks:
            - pc_network
    webserver:
        image: nginx:1.17
        ports:
            - ${WEB_PORT_AUTH}:8000
            - ${WEB_PORT_SSL_AUTH}:443
        volumes:
            - './container/nginx/config/nginx.conf:/etc/nginx/nginx.conf'
            - './container/nginx/config/default.conf:/etc/nginx/conf.d/default.conf'
            - './container/nginx/config/ssl_conf/:/etc/letsencrypt'
            - './container/nginx/config/ssl_data/:/var/www/certbot'
            - './log:/var/log/nginx/'
            - './appWeb/template/static/:/appWeb/static/'
        command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
        networks:
            - pc_network
    # certbot:
    #     image: certbot/certbot
    #     volumes:
    #         - './container/nginx/config/ssl_conf/:/etc/letsencrypt'
    #         - './container/nginx/config/ssl_data/:/var/www/certbot'
    #     entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    #     networks:
    #         - pc_network
networks:
    pc_network:
        driver: bridge